apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: argocd-kube
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      containers:
      - image: jeonggu1/docker-repo:c2466b4
        name: argocd-kube
